development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://.herokuapp.com"
  secret_token: "094ca74bbcf85455b2e71515418c9a719657bfc7a92c70679154ede95442a7de"
  signature_expiration: 3600 # one hour
